---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: metadata-server
  name: metadata-server
  namespace: nativemq
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8081
    - name: debug
      port: 5006
      protocol: TCP
      targetPort: 5006
    - name: grpc
      port: 9100
      protocol: TCP
      targetPort: 9100
  clusterIP: None
  selector:
    app: metadata-server
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: metadata-server
  namespace: nativemq
spec:
  replicas: 3
  selector:
    matchLabels:
      app: metadata-server
  serviceName: "metadata-server"
  template:
    metadata:
      labels:
        app: metadata-server
      namespace: nativemq
    spec:
      containers:
        - env:
            - name: QUARKUS_KUBERNETES_MOUNTS__METADATA_LOG_PVC__PATH
              value: /metadata/log/
            - name: JAVA_TOOL_OPTIONS
              value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5006"
          image: nativemq/metadata-server:1.0.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: metadata-server
          ports:
            - containerPort: 8081
              name: http
              protocol: TCP
            - containerPort: 5006
              name: debug
              protocol: TCP
            - containerPort: 9100
              name: grpc
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            grpc:
              port: 9100
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          resources:
            limits:
              cpu: 6000m
              memory: 1024Mi
            requests:
              cpu: 250m
              memory: 64Mi
          startupProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/started
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          volumeMounts:
            - mountPath: /metadata/log/
              name: metadata-log-pvc
              readOnly: false
      terminationGracePeriodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: metadata-log-pvc
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
        storageClassName: local-path
---